# Generated by Django 5.2.6 on 2025-10-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loan_borrower_name_alter_loan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('murabaha', 'Murabaha - Cost-Plus Financing'), ('ijarah', 'Ijarah - Leasing'), ('musharakah', 'Musharakah - Partnership')], default='murabaha', help_text='Islamic financing type', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='vehicle_make',
            field=models.CharField(blank=True, help_text='For car loans', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='For car loans', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='vehicle_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For car loans', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='vehicle_year',
            field=models.IntegerField(blank=True, help_text='For car loans', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='property_address',
            field=models.TextField(blank=True, help_text='For property loans', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For property loans', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.CharField(blank=True, choices=[('property', 'Property Purchase'), ('car', 'Car Purchase'), ('renovation', 'Renovation'), ('business', 'Business'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
