# Generated by Django 5.2.6 on 2026-01-04 07:49

import django.db.models.deletion
import loans.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login Attempt'), ('password_change', 'Password Changed'), ('profile_update', 'Profile Updated'), ('loan_created', 'Loan Application Created'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('payment_made', 'Payment Made'), ('document_uploaded', 'Document Uploaded'), ('verification_initiated', 'Verification Initiated'), ('verification_completed', 'Verification Completed'), ('data_export', 'Data Export Requested'), ('support_ticket_created', 'Support Ticket Created'), ('admin_action', 'Admin Action')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('loan_application', 'Loan Application'), ('payment', 'Payment Issue'), ('verification', 'Verification'), ('technical', 'Technical Issue'), ('complaint', 'Complaint'), ('other', 'Other')], default='general', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting on Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='verification',
            new_name='loans_verif_user_id_352530_idx',
            old_name='loans_verif_user_id_46d8ca_idx',
        ),
        migrations.RenameIndex(
            model_name='verification',
            new_name='loans_verif_status_69dea8_idx',
            old_name='loans_verif_status_c8e7d8_idx',
        ),
        migrations.AlterField(
            model_name='loan',
            name='address',
            field=loans.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='annual_income',
            field=loans.fields.EncryptedDecimalField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='credit_score',
            field=loans.fields.EncryptedIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='phone',
            field=loans.fields.EncryptedCharField(default='0000000000'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='property_address',
            field=loans.fields.EncryptedTextField(blank=True, help_text='For property loans', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='property_value',
            field=loans.fields.EncryptedDecimalField(blank=True, help_text='For property loans', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='vehicle_make',
            field=loans.fields.EncryptedCharField(blank=True, help_text='For car loans', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='vehicle_model',
            field=loans.fields.EncryptedCharField(blank=True, help_text='For car loans', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='vehicle_value',
            field=loans.fields.EncryptedDecimalField(blank=True, help_text='For car loans', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='vehicle_year',
            field=loans.fields.EncryptedIntegerField(blank=True, help_text='For car loans', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=loans.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='annual_income',
            field=loans.fields.EncryptedDecimalField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='credit_score',
            field=loans.fields.EncryptedIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=loans.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=loans.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loan'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='support_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.supportticket'),
        ),
        migrations.AddField(
            model_name='supportticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='loans.supportticket'),
        ),
        migrations.AddField(
            model_name='supportticketmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'status'], name='loans_suppo_user_id_0f1d41_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority'], name='loans_suppo_status_b24e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='loans_audit_user_id_107806_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='loans_audit_action_e68c67_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity'], name='loans_audit_severit_f0f619_idx'),
        ),
    ]
