# Generated by Django 5.2.6 on 2026-01-04 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_auditlog_supportticket_supportticketmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=50)),
                ('field_type', models.CharField(blank=True, max_length=20)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('access_type', models.CharField(choices=[('create', 'Token Created'), ('read', 'Token Read/Detokenized'), ('revoke', 'Token Revoked'), ('failed', 'Access Failed')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['token', 'accessed_at'], name='loans_token_token_983567_idx'), models.Index(fields=['accessed_by', 'access_type'], name='loans_token_accesse_4f0a66_idx'), models.Index(fields=['field_type', 'accessed_at'], name='loans_token_field_t_5967aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Token reference (e.g., tok_abc123)', max_length=50, unique=True)),
                ('encrypted_value', models.TextField(help_text='AES-256 encrypted data')),
                ('encrypted_data_key', models.TextField(help_text='KMS-encrypted data encryption key')),
                ('field_type', models.CharField(db_index=True, help_text='Type of data (ssn, income, bank_account, etc.)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('is_revoked', models.BooleanField(default=False, help_text='Token revoked for security')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tokens', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='loans_token_token_62f89b_idx'), models.Index(fields=['field_type'], name='loans_token_field_t_1c652a_idx'), models.Index(fields=['created_by', 'field_type'], name='loans_token_created_69293f_idx'), models.Index(fields=['is_revoked'], name='loans_token_is_revo_872368_idx')],
            },
        ),
    ]
