# Generated by Django 5.2.6 on 2026-01-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_tokenaccesslog_tokenvault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='address',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='property_value',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='vehicle_value',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='vehicle_year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='loan',
            name='address_token',
            field=models.CharField(blank=True, help_text='Token for encrypted address', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='annual_income_token',
            field=models.CharField(blank=True, help_text='Token for encrypted annual income', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='bank_account_token',
            field=models.CharField(blank=True, help_text='Token for encrypted bank account', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_score_token',
            field=models.CharField(blank=True, help_text='Token for encrypted credit score', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='phone_token',
            field=models.CharField(blank=True, help_text='Token for encrypted phone', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='property_address_token',
            field=models.CharField(blank=True, help_text='Token for encrypted property address', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='property_value_token',
            field=models.CharField(blank=True, help_text='Token for encrypted property value', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='ssn_token',
            field=models.CharField(blank=True, help_text='Token for encrypted SSN', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='vehicle_make_token',
            field=models.CharField(blank=True, help_text='Token for encrypted vehicle make', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='vehicle_model_token',
            field=models.CharField(blank=True, help_text='Token for encrypted vehicle model', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='vehicle_value_token',
            field=models.CharField(blank=True, help_text='Token for encrypted vehicle value', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='vehicle_year_token',
            field=models.CharField(blank=True, help_text='Token for encrypted vehicle year', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_token',
            field=models.CharField(blank=True, help_text='Token for encrypted address', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='annual_income_token',
            field=models.CharField(blank=True, help_text='Token for encrypted income', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credit_score_token',
            field=models.CharField(blank=True, help_text='Token for encrypted credit score', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='national_id_token',
            field=models.CharField(blank=True, help_text='Token for encrypted national ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_token',
            field=models.CharField(blank=True, help_text='Token for encrypted phone', max_length=50, null=True),
        ),
    ]
