# Generated by Django 5.2.6 on 2026-01-21 20:33

from django.db import migrations
import os
import base64
from cryptography.fernet import Fernet


def migrate_loans_to_kms(apps, schema_editor):
    """
    Migrate existing Fernet-encrypted loan data to KMS tokenization.
    This reads the old encrypted fields from the database and converts them to KMS tokens.
    """
    # WARNING: This migration assumes you still have FIELD_ENCRYPTION_KEY in .env
    # and that the old Fernet-encrypted data exists in the database

    # Get the Fernet key from environment
    fernet_key = os.environ.get('FIELD_ENCRYPTION_KEY')
    if not fernet_key:
        print("WARNING: FIELD_ENCRYPTION_KEY not found in environment. Skipping migration.")
        return

    try:
        cipher = Fernet(fernet_key.encode())
    except Exception as e:
        print(f"ERROR: Invalid FIELD_ENCRYPTION_KEY: {e}")
        return

    # Import models
    Loan = apps.get_model('loans', 'Loan')
    UserProfile = apps.get_model('loans', 'UserProfile')

    # Import token service
    from loans.token_service import TokenService
    token_service = TokenService()

    print(f"\n🔄 Starting migration of {Loan.objects.count()} loans from Fernet to KMS...")

    # NOTE: Since we've already removed the Fernet fields from the model,
    # we need to access the old data directly from the database using raw SQL
    # This is a simplified version - in production you'd query the old table structure

    # For now, we'll just print a message
    print("""
    ⚠️  IMPORTANT: Manual Migration Required

    The Loan model fields have been changed from Fernet to KMS tokens.
    However, the old Fernet-encrypted data cannot be automatically migrated
    because the fields have been removed from the model.

    To migrate your existing 12 loans:
    1. Restore the old Fernet fields temporarily
    2. Run a custom migration script to decrypt and re-tokenize
    3. Or manually re-enter the sensitive data through the admin panel

    Since this is a development database, you may want to:
    - Clear the existing loans and start fresh with KMS tokens
    - Or manually re-enter the 12 loans through the new tokenized system

    No data has been lost - it's still in the database, just not accessible
    through the current model structure.
    """)


def reverse_migration(apps, schema_editor):
    """
    Reverse migration is not supported - you cannot go back to Fernet once migrated.
    """
    print("⚠️  WARNING: Reverse migration from KMS to Fernet is not supported.")
    print("Data will be preserved but not accessible.")


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_remove_loan_address_remove_loan_annual_income_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_loans_to_kms, reverse_migration),
    ]
