# Generated by Django 5.2.6 on 2026-02-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_migrate_fernet_to_kms'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email verification status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When email was verified', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lender_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual Lender'), ('organization', 'Organization')], help_text='Type of lender (individual/organization)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization name for organizational lenders', max_length=255, null=True),
        ),
    ]
